### ISSUE TITLE
problem with inference of covid-net-ct-a

### ISSUE THREAD

**Issue by jomollin** [haydengunraj/COVIDNet-CT#5] opened 2020-09-16 19:14 UTC
Hi,
I try to inference a CT image

CALL:
python c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py --input_height 100 --input_width 100 --auto_crop --model_dir C:/covid-net/COVIDNet-CT-master/COVIDNet-CT-A --meta_name model.meta --ckpt_name model --image_file c:/test/a5ae5a83-a71d-4515-87df-6f15f691e166.jpg

RESULT:
C:\ProgramData\Anaconda3\lib\site-packages\dask\config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 318, in <module>
    mode, args = parse_args(sys.argv[1:])
  File "c:\covid-net\COVIDNet-CT-master\utils.py", line 57, in parse_args
    raise ValueError('Mode must be one of {train, test, infer} or {-h, --help}')
ValueError: Mode must be one of {train, test, infer} or {-h, --help}

Can you please correct me, what am I doing wrong

best regards
Joachim

**Comment by haydengunraj** [comment] 2020-09-16 19:32
Hi Joachim,

The run_covidnet_ct.py script handles training, validation/testing and inference. As such, there is a required `mode` argument that should precede all other arguments, i,e,:
`python run_covidnet_ct.py **infer** --input_height 512 --input_width 512 --auto_crop ...`

One other thing to note is that the current COVIDNet-CT models take input images of size 512x512. You will get a shape-related error if you set `--input_height 100 --input_width 100`. These arguments are included in case we add new models with different input shapes, but for now they should be left as the default 512x512.

**Comment by jomollin** [comment] 2020-09-17 06:46
Hi Haydengunraj,
thanks for the quick help. I installed the new version and followed your advises, but get now a lot more errors. As I'm not very familiar with python, I need some help for just do inference with your models:

OUTPUT:
2020-09-17 08:41:19.634355: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-09-17 08:41:19.639191: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Loading meta graph from C:/covid-net/COVIDNet-CT-master/COVIDNet-CT-A\model.meta
Traceback (most recent call last):
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 372, in <module>
    runner.infer(args.image_file, args.auto_crop)
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 244, in infer
    graph, sess, saver = self.load_graph()
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 121, in load_graph
    saver = tf.train.import_meta_graph(self.meta_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'FusedBatchNormV3'

best regards
Joachim

**Comment by jomollin** [comment] 2020-09-17 11:18
Dear Haydengunraj,

thanks for your help. But unfortunately I run into other problems. I've downloaded the newest version. Must remark line 13 because it failed to load ConfusionMatrixDisplay.

python c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py infer --input_height 512 --input_width 512 --auto_crop --model_dir C:/covid-net/COVIDNet-CT-master/COVIDNet-CT-A --meta_name model.meta --ckpt_name model --image_file c:/test/a5ae5a83-a71d-4515-87df-6f15f691e166.jpg

gives now

2020-09-17 13:17:03.331029: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-09-17 13:17:03.332444: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Loading meta graph from C:/covid-net/COVIDNet-CT-master/COVIDNet-CT-A\model.meta
Traceback (most recent call last):
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 373, in <module>
    runner.infer(args.image_file, args.auto_crop)
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 245, in infer
    graph, sess, saver = self.load_graph()
  File "c:/covid-net/COVIDNet-CT-master/run_covidnet_ct.py", line 122, in load_graph
    saver = tf.train.import_meta_graph(self.meta_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'FusedBatchNormV3'

**Comment by haydengunraj** [comment] 2020-09-17 19:53
Could you specify which TensorFlow version you're using? This may be due to a version mismatch.

**Comment by jomollin** [comment] 2020-09-18 09:44
I'm using Tensorflow 1.13.1 which is perfectly running with covid-net. Therefor I hesitate to upgrade

**Comment by haydengunraj** [comment] 2020-09-19 03:08
COVIDNet-CT has only been tested with TensorFlow 1.15, so it's difficult for me to say what the problem is. My best guess is that the FusedBatchNormV3 op in 1.15 is not supported by 1.13.1, but again this is a guess. Your best bet might be to upgrade to 1.15, as both COVID-Net and COVIDNet-CT are tested on 1.15.

**Comment by jomollin** [comment] 2020-09-19 11:25
I solved the problem by upgrading to Tensorflow 1.15. Perfect. You have done great work. Thank you.

I'm not very familiar with Python and looking for some help to make the inference request available as a local web service, to which I can communicate with JSON. Any idea?

**Comment by haydengunraj** [comment] 2020-09-19 23:33
I'm not too familiar with building web services, so I won't be able to help you on that end.

**Comment by haydengunraj** [comment] 2020-09-19 23:34
I'm closing this issue now, as the original problem was resolved as a version issue. The question about web services is best asked elsewhere, as issues should be limited to problems with the code, questions about the code/methodology, or potential enhancements.

**Closed by haydengunraj** 2020-09-19 23:34 UTC
